"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InjectorToken = exports.Injector = exports.StaticInjector = exports.registryProvider = exports.getProvider = exports.Injectable = exports.Inject = void 0;
var injectable_1 = require("./injectable");
Object.defineProperty(exports, "Inject", { enumerable: true, get: function () { return injectable_1.Inject; } });
Object.defineProperty(exports, "Injectable", { enumerable: true, get: function () { return injectable_1.Injectable; } });
Object.defineProperty(exports, "getProvider", { enumerable: true, get: function () { return injectable_1.getProvider; } });
Object.defineProperty(exports, "registryProvider", { enumerable: true, get: function () { return injectable_1.registryProvider; } });
var injector_1 = require("./injector");
Object.defineProperty(exports, "StaticInjector", { enumerable: true, get: function () { return injector_1.StaticInjector; } });
var injector_abstract_1 = require("./injector.abstract");
Object.defineProperty(exports, "Injector", { enumerable: true, get: function () { return injector_abstract_1.Injector; } });
var injector_token_1 = require("./injector-token");
Object.defineProperty(exports, "InjectorToken", { enumerable: true, get: function () { return injector_token_1.InjectorToken; } });
